version: '3.8'

services:
  db:
    image: postgres:15
    container_name: notificaciones_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: agm_notificaciones_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: notificaciones_api
    restart: always
    ports:
      - "8005:8005"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      # Para que los cambios en el código se reflejen en tiempo real sin tener que reconstruir
      - .:/app
      - ../proto:/app/proto
      - /app/venv # Ignorar el venv local dentro del contenedor

volumes:
  postgres_data:
