services:
  asistencias_db:
    image: postgres:15-alpine
    container_name: asistencias_db
    restart: always
    environment:
      POSTGRES_USER: agm_user
      POSTGRES_PASSWORD: agm_password
      POSTGRES_DB: agm_asistencias_db
    ports:
      - "5432:5432"
    volumes:
      - asistencias_db_data:/var/lib/postgresql/data

  ms-asistencias:
    build:
      context: ./ms-asistencias
      dockerfile: Dockerfile
    container_name: ms-asistencias
    restart: always
    ports:
      - "8005:8005"
      - "50055:50055"
    environment:
      - ENVIRONMENT=production
      # Nota: Usamos 'asistencias_db' como host para que apunte al contenedor de BD
      - DATABASE_URL=postgresql+asyncpg://agm_user:agm_password@asistencias_db:5432/agm_asistencias_db
      - QR_SECRET_KEY=bWlfY2xhdmVfc2VjcmV0YV9wYXJhX2NpZnJhcl9xcg==
      - QR_TTL_SECONDS=20
      - SESSION_DURATION_MINUTES=10
      - PRESENT_LIMIT_MINUTES=5
    depends_on:
      - asistencias_db

  auth_db:
    image: postgres:15-alpine
    container_name: auth_db
    restart: always
    environment:
      POSTGRES_USER: agm_auth_user
      POSTGRES_PASSWORD: agm_auth_password
      POSTGRES_DB: agm_auth_db
    ports:
      - "5434:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  ms-auth:
    build:
      context: ./ms-auth
      dockerfile: Dockerfile
    container_name: ms-auth
    restart: always
    ports:
      - "8001:8001"
      - "50051:50051"
    environment:
      - DATABASE_URL=postgresql://agm_auth_user:agm_auth_password@auth_db:5432/agm_auth_db
      - API_HOST=0.0.0.0
      - API_PORT=8001
      - GRPC_HOST=0.0.0.0
      - GRPC_PORT=50051
      - JWT_SECRET_KEY=change-this-secret-key
    depends_on:
      - auth_db

  db-docentes:
    image: postgres:15-alpine
    container_name: db-docentes-alumnos
    restart: always
    environment:
      POSTGRES_USER: agm_docentes_user
      POSTGRES_PASSWORD: agm_docentes_password
      POSTGRES_DB: agm_docentes_alumnos_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_ms3:/var/lib/postgresql/data

  ms-docentes-alumnos:
    build:
      context: ./ms-docentes-alumnos
      dockerfile: Dockerfile
    container_name: ms-docentes-alumnos
    restart: always
    ports:
      - "8003:8003"
      - "50053:50053"
    environment:
      - DATABASE_URL=postgresql://agm_docentes_user:agm_docentes_password@db-docentes:5432/agm_docentes_alumnos_db
      - REST_PORT=8003
      - MS1_HOST=ms-auth
      - MS1_PORT=50051
    depends_on:
      - db-docentes
      - ms-auth

volumes:
  asistencias_db_data:
  auth_db_data:
  postgres_data_ms3:
