services:
  ms-periodos-materias-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-periodos-materias-api
    env_file:
      - .env.production
    ports:
      - "${REST_PORT:-8002}:8002"
      - "${GRPC_PORT:-50052}:50052"
    depends_on:
      ms-periodos-materias-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - ms-periodos-materias-network

  ms-periodos-materias-db:
    image: postgres:16
    container_name: ms-periodos-materias-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agm_periodos_db
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - ms-periodos-materias-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d agm_periodos_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - ms-periodos-materias-network

volumes:
  ms-periodos-materias-db-data:

networks:
  ms-periodos-materias-network:
    driver: bridge